database/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from database.views import *

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("search/", SearchView.as_view(), name="search"),
    path("archives/<int:pk>", ArchiveDetailView.as_view(), name="archive-detail"),
    path("archives/", ArchiveListView.as_view(), name="archive-list"),
    path("create/", CreationView.as_view(), name="create"),
    path(
        "contributions/",
        ContributionMusicalWorkListView.as_view(),
        name="contributionmusicalwork-list",
    ),
    path(
        "contributions/<int:pk>",
        ContributionMusicalWorkListView.as_view(),
        name="contributionmusicalwork-detail",
    ),
    path(
        "encodingworkflows/",
        EncodingWorkflowListView.as_view(),
        name="encodingworkflows-list",
    ),
    path(
        "encodingworkflows/<int:pk>",
        EncodingWorkflowDetailView.as_view(),
        name="encodingworkflow-detail",
    ),
    path(
        "experimentalstudies",
        ExperimentalStudyListView.as_view(),
        name="experimentalstudy-list",
    ),
    path(
        "experimentalstudies/<int:pk>",
        ExperimentalStudyDetailView.as_view(),
        name="experimentalstudy-detail",
    ),
    path(
        "extractedfeatures",
        ExtractedFeatureListView.as_view(),
        name="extractedfeature-list",
    ),
    path(
        "extractedfeatures/<int:pk>",
        ExtractedFeatureDetailView.as_view(),
        name="extractedfeature-detail",
    ),
    path("featurefiles/", FeatureFileListView.as_view(), name="featurefile-list"),
    path(
        "featurefiles/<int:pk>",
        FeatureFileDetailView.as_view(),
        name="featurefile-detail",
    ),
    path("featuretypes/", FeatureTypeListView.as_view(), name="featuretype-list"),
    path(
        "featuretypes/<int:pk>",
        FeatureTypeListView.as_view(),
        name="featuretype-detail",
    ),
    path(
        "file-create/", FileCreationView.as_view(), name="file-creation",
    ),
    path("files/", FileListView.as_view(), name="file-list"),
    path("files/<int:pk>", FileDetailView.as_view(), name="file-detail"),
    path("styles/", GenreAsInStyleListView.as_view(), name="genreasinstyle-detail"),
    path(
        "styles/<int:pk>",
        GenreAsInStyleDetailView.as_view(),
        name="genreasinstyle-detail",
    ),
    path("types/", GenreAsInTypeListView.as_view(), name="genreasintype-list"),
    path(
        "types/<int:pk>", GenreAsInTypeDetailView.as_view(), name="genreasintype-detail"
    ),
    path("areas/", GeographicAreaListView.as_view(), name="geographicarea-list"),
    path(
        "areas/<int:pk>",
        GeographicAreaDetailView.as_view(),
        name="geographicarea-detail",
    ),
    path("instruments/", InstrumentListView.as_view(), name="instrument-list"),
    path(
        "instruments/<int:pk>", InstrumentDetailView.as_view(), name="instrument-detail"
    ),
    path("languages/", LanguageListView.as_view(), name="language-list"),
    path("languages/<int:pk>", LanguageDetailView.as_view(), name="language-detail"),
    path(
        "musicalworks/<int:pk>",
        MusicalWorkDetailView.as_view(),
        name="musicalwork-detail",
    ),
    path("musicalworks/", MusicalWorkListView.as_view(), name="musicalwork-list"),
    path("parts/", PartListView.as_view(), name="part-list"),
    path("parts/<int:pk>", PartDetailView.as_view(), name="part-detail"),
    path("persons/<int:pk>", PersonDetailView.as_view(), name="person-detail"),
    path("persons/", PersonListView.as_view(), name="person-list"),
    path(
        "researchcorpora/", ResearchCorpusListView.as_view(), name="researchcorpus-list"
    ),
    path(
        "researchcorpora/<int:pk>",
        ResearchCorpusDetailView.as_view(),
        name="researchcorpus-detail",
    ),
    path("sections/", SectionListView.as_view(), name="section-list"),
    path("sections/<int:pk>", SectionDetailView.as_view(), name="section-detail"),
    path("softwares/", SoftwareListView.as_view(), name="software-list"),
    path("softwares/<int:pk>", SoftwareDetailView.as_view(), name="software-detail"),
    path("sources/", SourceListView.as_view(), name="source-list"),
    path("sources/<int:pk>", SourceDetailView.as_view(), name="source-detail"),
    path("typesofsection/", TypeOfSectionListView.as_view(), name="typeofsection-list"),
    path(
        "typesofsection/<int:pk>",
        TypeOfSectionDetailView.as_view(),
        name="typeofsection-detail",
    ),
    path(
        "validationworkflows/",
        ValidationWorkFlowListView.as_view(),
        name="validationworkflow-list",
    ),
    path(
        "validationworkflows/<int:pk>",
        ValidationWorkFlowDetailView.as_view(),
        name="validationworkflow-detail",
    ),
    path("download/content/<int:pk>", download_content_file, name="download-content"),
    path("download/feature/<int:pk>", download_feature_file, name="download-feature"),
    path("download/cart/", download_cart, name="download-cart"),
    path("cart/", CartView.as_view(), name="cart"),
    path("ajax/add_to_cart/", add_to_cart, name="add-to-cart"),
    path("ajax/remove_from_cart/", remove_from_cart, name="remove-from-cart"),
    path("ajax/clear_cart/", clear_cart, name="clear-cart"),
    # autocomplete views
    path("type-autocomplete/", TypeAutocomplete.as_view(), name="type-autocomplete"),
    path("file-autocomplete/", FileAutocomplete.as_view(), name="file-autocomplete"),
    path('instrument-autocomplete/', InstrumentAutocomplete.as_view(), name='instrument-autocomplete'),
    path('geographicarea-autocomplete/', GeographicAreaAutocomplete.as_view(), name='geographicarea-autocomplete'),
    path('software-autocomplete/', SoftwareAutocomplete.as_view(), name='software-autocomplete'),
    path('archive-autocomplete/', ArchiveAutocomplete.as_view(), name='archive-autocomplete'),
    path('style-autocomplete/', StyleAutocomplete.as_view(), name='style-autocomplete'),
    path('musicalwork-autocomplete/', MusicalWorkAutocomplete.as_view(), name='musicalwork-autocomplete'),
    path('person-autocomplete/', PersonAutocomplete.as_view(), name='person-autocomplete'),
    path('ajax/create-type-function/', create_type, name='create-type-function'),
    path('ajax/create-style-function/', create_style, name='create-style-function'),
    path('ajax/create-instrument-function/', create_instrument, name='create-instrument-function'),
    path('ajax/create-geographic-area-function/', create_geographic_area, name='create-geographic-area-function'),
]

simssadb/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""simssadb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from django.contrib.auth import views
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    re_path(r"", include("database.urls")),
    re_path(r"accounts/login/$", views.LoginView.as_view, name="login"),
    re_path(
        r"accounts/logout/$", views.LogoutView.as_view, name="logout", kwargs={"next_page": "/"}
    ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = [re_path(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

database/models/contributed_to.py
"""Define a ContributedTo model"""
from django.contrib.postgres.fields import DateRangeField
from django.core.exceptions import ValidationError
from django.db import models

from database.utils.model_utils import clean_date
from database.models.custom_base_model import CustomBaseModel
from database.models.geographic_area import GeographicArea
from database.models.musical_work import MusicalWork
from database.models.part import Part
from database.models.person import Person
from database.models.section import Section


class ContributedTo(CustomBaseModel):
    """ Relate a person that made a Contribution to a Musical Work/Section/Part

    A ContributedToModel provides a many-to-many relationship with attributes
    between one of Musical Work, Section or Part to Person.

    A Musical Work/Section/Part can have many contributors with different roles
    i.e. a person composed a piece, two others arranged it, another wrote the
    lyrics

    ContributedTo.person : models.ForeignKey
        Reference to a Person that made this Contribution to a Musical Work,
        Section or Part

    ContributedTo.certainty_of_attribution : models.BooleanField
        Whether it is certain if this Person made this Contribution

    ContributeTo.role : models.CharField
        The role that this Person had in contributing. Can be one of: Composer,
        Arranger, Author of Text, Transcriber, Improviser, Performer

    ContributedTo.date : postgres.fields.DateRangeField
        The date in which this Contribution happened

    ContributedTo.location : models.ForeignKey
        Reference to the GeographicArea in which this Contribution happened

    ContributedTo.contributed_to_part : models.ForeignKey
        Reference to the Part to which this Contribution was made

    ContributedTo.contributed_to_section : models.ForeignKey
        Reference to the Section to which this Contribution was made

    ContributedTo.contributed_to_work : models.ForeignKey
        Reference to the MusicalWork to which this Contribution was made

    See Also
    --------
    database.models.CustomBaseModel
    database.models.Person
    database.models.MusicalWork
    database.models.Section
    database.models.Part
    database.models.GeographicArea

    """

    ROLES = (
        ('COMPOSER', 'Composer'),
        ('ARRANGER', 'Arranger'),
        ('AUTHOR', 'Author of Text'),
        ('TRANSCRIBER', 'Transcriber'),
        ('IMPROVISER', 'Improviser'),
        ('PERFORMER', 'Performer'),
        )
    person = models.ForeignKey(Person, on_delete=models.PROTECT,
                               related_name='contributed_to',
                               help_text='The Person that contributed to a'
                                         'Musical Work, Section or Part')
    certain = models.BooleanField(default=True, null=False,
                                  blank=False,
                                  help_text='Whether it is '
                                            'certain if this '
                                            'Person made this '
                                            'contribution')
    role = models.CharField(default="COMPOSER", max_length=30, choices=ROLES,
                            help_text='The role that this Person had in '
                                      'contributing. Can be one of: Composer, '
                                      'Arranger, Author of Text, Transcriber, '
                                      'Improviser, Performer')
    date = DateRangeField(null=True, blank=True,
                          help_text='The date in which this contribution '
                                    'happened')
    location = models.ForeignKey(GeographicArea, on_delete=models.SET_NULL,
                                 null=True, blank=True,
                                 help_text='The location in which this '
                                           'contribution happened')

    contributed_to_part = models.ForeignKey(Part, null=True,
                                            blank=True,
                                            on_delete=models.CASCADE,
                                            related_name='contributed_to',
                                            help_text='The Part that the '
                                                      'Person contributed to')
    contributed_to_section = models.ForeignKey(Section, null=True,
                                               blank=True,
                                               on_delete=models.CASCADE,
                                               related_name='contributed_to',
                                               help_text='The Section that the '
                                                         'Person contributed to'
                                               )
    contributed_to_work = models.ForeignKey(MusicalWork, null=True,
                                            blank=True,
                                            on_delete=models.CASCADE,
                                            related_name='contributed_to',
                                            help_text='The Musical Work that '
                                                      'the Person contributed '
                                                      'to')

    class Meta(CustomBaseModel.Meta):
        db_table = 'contributed_to'
        verbose_name_plural = 'Contributed To Relationships'
        # Adding the same constraints as the clean method but on the DB level
        db_constraints = {
            'at_least_one_is_not_null': 'check (contributed_to_section_id is '
                                        'not null or contributed_to_part_id '
                                        'is not null or '
                                        'contributed_to_work_id is not null)',
            'work_unique':              'check (NOT (contributed_to_work_id is '
                                        'not null '
                                        'and (contributed_to_section_id is not '
                                        'null or '
                                        'contributed_to_part_id is not null)))',
            'section_unique':           'check (NOT (contributed_to_section_id '
                                        'is not '
                                        'null '
                                        'and (contributed_to_work_id is not '
                                        'null or '
                                        'contributed_to_part_id is not null)))',
            'part_unique':              'check (NOT (contributed_to_part_id is '
                                        'not null '
                                        'and (contributed_to_section_id is not '
                                        'null or '
                                        'contributed_to_work_id is not null)))'
            }

    def __str__(self):
        if self.contributed_to_part_id is not None:
            return "{0}, {1} of {2}".format(self.person, self.role.lower(),
                                            self.contributed_to_part)
        if self.contributed_to_section_id is not None:
            return "{0}, {1} of {2}".format(self.person, self.role.lower(),
                                            self.contributed_to_section)
        if self.contributed_to_work_id is not None:
            return "{0}, {1} of {2}".format(self.person, self.role.lower(),
                                            self.contributed_to_work)

    def clean(self):
        """ Enforce the integrity of the relationship.

        Ensure that at least one and only one of Musical Work/Section/Part
        is not null.

        Raises
        ------
        ValidationError
            If more than one out Musical Work, Section or Part are not null
            or if all three are null

        """
        if self.contributed_to_part_id is not None:
            if self.contributed_to_section_id is not None or \
                    self.contributed_to_work_id is not None:
                raise ValidationError('Only one of Work, Section or '
                                      'Part must be not null')
        if self.contributed_to_section_id is not None:
            if self.contributed_to_part_id is not None or \
                    self.contributed_to_work_id is not None:
                raise ValidationError('Only one of Work, Section or '
                                      'Part must be not null')
        if self.contributed_to_work_id is not None:
            if self.contributed_to_part_id is not None or \
                    self.contributed_to_section_id is not None:
                raise ValidationError('Only one of Work, Section or '
                                      'Part must be not null')
        if self.contributed_to_section_id is None and \
                self.contributed_to_part_id is None and \
                self.contributed_to_work_id is None:
            raise ValidationError('At least one of Work, Section or Part '
                                  'must be not null')
        super(CustomBaseModel, self).clean()

    def save(self, *args, **kwargs):
        """Save the current instance.

        Overrides the parent method to ensure that clean() is called before
        actually saving.

        """
        self.full_clean()
        super(CustomBaseModel, self).save()

database/templates/database/base.html
<!doctype html>
{% load static %}
{% load i18n %}
<html lang="en">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicon and title -->
    <link rel="icon" href="{% static "favicon.ico" %}">
    <title>SIMSSA Database</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- jQuery Ui CSS -->
    <link rel="stylesheet" href="{% static "css/jquery-ui.min.css" %}">
    <!--Font Awesome CSS, for icons-->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <!-- jQuery UI -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <!-- Enable Select2 for auto-complete -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <style>
        html {
            position: relative;
            min-height: 90%;
        }

        body {
            margin-bottom: 30px;
            /* Margin bottom by footer height */
        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 30px;
            /* Set the fixed height of the footer here */
            line-height: 30px;
            /* Vertically center the text there */
        }
    </style>
</head>

<body>

    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand text-light" href="{% url 'home' %}"> SIMSSA Database </a>

            <!-- Hamburger button to show nav when screen is smaller-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!--This div collapses or expands according to the button above-->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!--This ul is the one with all the nav bar items but not the search-->
                <ul class="navbar-nav mr-auto">

                    <!--About link-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">
                            {% trans "About" %}
                        </a>
                    </li>

                    <!--Dropdown menu for Browse-->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            {% trans "Browse" %}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href={% url 'musicalwork-list' %}>{% trans "Musical Works" %}</a>
                            <a class="dropdown-item" href={% url 'person-list' %}>{% trans "Persons" %}</a>
                            <a class="dropdown-item" href={% url 'researchcorpus-list' %}>
                                {% trans "Research Corpora" %} </a>
                        </div>
                    </li>


                    <!--Download Cart-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cart' %}">
                            <span class="fa fa-shopping-cart"></span> {% trans "Download Cart" %}
                        </a>
                    </li>

                    <!-- Upload dropdown -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create' %}">
                            {% trans "Upload" %}
                        </a>
                    </li>

                </ul>

                <!-- Search bar-->
                {% if not "search" in request.path or "research" in request.path %}
                <form class="form-inline my-2 my-lg-0" method="get" action="/search/">
                    <div class="input-group mr-sm-2">
                        <div class="input-group-prepend">
                            <button class="btn btn-primary my-2 my-sm-0" type="submit">
                                <span class="fa fa-search"></span>
                            </button>
                        </div>
                        <input type="text" class="form-control mr-sm-2" placeholder="Search" aria-label="Search"
                            name="q" aria-describedby="basic-addon1">
                    </div>
                </form>
                {% endif %}
            </div>
        </nav>
    </header>

    <!-- Content goes here, using the extends tag from Django -->
    <main role="main" class="content container pt-5">
        {% block content %}
        {% endblock %}
    </main>

    <!-- Footer in every page -->
    <footer class="footer">
        <hr>
        <div class="container d-flex justify-content-center">
            <nav class="nav nav-pills flex-column flex-sm-row">
                <a class="flex-sm-fill text-sm-center nav-link" href="https://linkedmusic.ca/" target="_blank">LinkedMusic</a>
                <a class="flex-sm-fill text-sm-center nav-link" href="http://www.mcgill.ca/music/"
                    target="_blank">Schulich School of Music</a>
                <a class="flex-sm-fill text-sm-center nav-link" href="https://www.marianopolis.edu/" target="_blank">Marianopolis College</a>
                <a class="flex-sm-fill text-sm-center nav-link" href="http://www.cirmmt.org" target="_blank">CIRMMT</a>
                <a class="flex-sm-fill text-sm-center nav-link" href="http://simssa.ca" target="_blank">SIMSSA</a>
                <a class="flex-sm-fill text-sm-center nav-link" href="http://elvisproject.ca" target="_blank">ELVIS
                    Project</a>
                <a class="flex-sm-fill text-sm-center nav-link" href="https://github.com/ELVIS-Project/simssadb"
                    target="_blank">SIMSSA DB GitHub Repo</a>
            </nav>
        </div>
        <br>
    </footer>
</body>

</html>

database/templates/database/collectionofsources_detail.html
{% extends "database/base.html" %}

{% block content %}
    {% include 'database/detail_title.html' with object=collection_of_sources %}
<dl class="row">
    {% if collection_of_sources.editorial_notes %}
        <dt class="col-sm-3">
            Editorial Notes
        </dt> 
        <dd class="col-sm-9">
           {{ collection_of_sources.editorial_notes }}
        </dd>
    {% endif %}

    {% if collection_of_sources.url %}
        <dt class="col-sm-3">
            URL
        </dt>
        <dd class="col-sm-9">
            <a href="{{ collection_of_sources.url }}">{{ collection_of_sources.url }}</a>
        </dd>
    {% endif %}

    {% if collection_of_sources.person_publisher %}
        <dt class="col-sm-3">
            Person Publisher
        </dt> 
        <dd class="col-sm-9">
           {{ collection_of_sources.person_publisher}}
        </dd>
    {% endif %}

    {% if collection_of_sources.archive %}
        <dt class="col-sm-3">
            Archive
        </dt> 
        <dd class="col-sm-9">
           {{ collection_of_sources.archive }}
        </dd>
    {% endif %}

    {% if collection_of_sources.sources.exists %}
        <dt class="col-sm-3"> Source{{ source.sources.all|pluralize }} </dt>
        <dd class="col-sm-9">
            {% for child in collection_of_sources.sources.all %}
                    <a href="{{ child.get_absolute_url }}">{{ child }}</a>{% if not forloop.last %},{% endif %}
            {% endfor %}
        </dd>
    {% endif %}
    
</dl>
{% endblock %}

database/templates/database/detail.html
{% extends "database/base.html" %}
{% block content %}
{% include 'database/detail_title.html' with object=object%}
{% endblock %}

database/templates/database/detail_title.html
<div class=row>
    <div class="col-sm-6"> 
        <p class="text-muted"> 
            {{ object.get_verbose_name|title }}
        </p>
    </div>
    <div class="col-sm-6" align="right"> 
        <p class="text-muted">
            Last modified on: {{ object.date_updated }}
        </p>
    </div>
</div>
<h3> {{ object }} </h3>
<br>

database/templates/database/geographicarea_detail.html
{% extends "database/base.html" %}

{% block content %}
{% include 'database/detail_title.html' with object=geographic_area %}

<dl class="row">
{% if geographic_area.part_of %}
    <dt class="col-sm-3">
        Part Of:
    </dt>
    <dd class="col-sm-9">
        <a href="{{ geographic_area.part_of.get_absolute_url }}">{{ geographic_area.part_of }}</a>
    </dd>
{% endif %}
</dl>

<dl class="row">
{% if geographic_area.child_areas.exists %}
    <dt class="col-sm-3">
        Sub-Areas:
    </dt>
    <dd class="col-sm-9">
         {% for area in geographic_area.child_areas.all %}
                <a href="{{ area.get_absolute_url }}">{{ area }}{% if not forloop.last %},{% endif %} </a>
            {% endfor %}
    </dd>
{% endif %}
</dl>


{% if geographic_area.birth_location_of.exists %}
<h4> Persons Born in this Area </h4>
<ul class="list-group">
{% for person in geographic_area.birth_location_of.all %}
    <li class="list-group-item">
        <a href="{{person.get_absolute_url}}"> {{ person }}</a>
    </li>
{% endfor %}
</ul>
{% endif %}

{% if geographic_area.musical_works.exists %}
<h4> Musical Works Written in this Area </h4>
<ul class="list-group">
{% for work in geographic_area.musical_works %}
    <li class="list-group-item">
        <a href="{{work.get_absolute_url}}"> {{ work }}</a>
    </li>
{% endfor %}
</ul>
{% endif %}

{% if geographic_area.section.exists %}
<h4> Sections Written in this Area </h4>
<ul class="list-group">
{% for section in geographic_area.sections %}
    <li class="list-group-item">
        <a href="{{section.get_absolute_url}}"> {{ section }}</a>
    </li>
{% endfor %}
</ul>
{% endif %}

{% endblock %}

database/templates/database/instrument_detail.html
{% extends "database/base.html" %}

{% block content %}
{% include 'database/detail_title.html' with object=instrument %}

{% if instrument.parts.exists %}
<h4> Parts Written for this Instrument </h4>
<ul class="list-group">
{% for part in instrument.parts.all %}
    <li class="list-group-item">
        <a href="{{ part.get_absolute_url }}"> {{ part }}</a>
    </li>
{% endfor %}
</ul>
{% endif %}

{% endblock %}

database/templates/database/list.html
{% extends "database/base.html" %}
{% load template_helpers %}
{% block content %}

{% include "list_filter_form.html" %}
{% include "list_pagination.html" with page_obj=object_list %}

<ul class="list-group">
{% for object in object_list %}
   <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="flex-column align-items-start">
            <a href="{{ object.get_absolute_url }}"> {{ object }} </a>
        </div>
    </li>
{% endfor %}
</ul>

{% include "list_pagination.html" with page_obj=object_list %}
{% endblock %}

database/templates/database/list_filter_form.html
<div class="form-row align-items-right">
    <h3 class="col-sm-6"> {{ object_list.model.get_verbose_name_plural }} 
        {% if is_paginated %}
            ({{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }})
        {% else %}
            ({{page_obj.paginator.count}})
        {% endif %}
    </h3>
    <form method="get" class="col-sm-6">
        <div class="input-group input-group-sm">
            {% if object_list.model.get_verbose_name == "person" %}
                <script>
                    $(function() {
                        var temp="{{ request.GET.role }}"; 
                        $("#id_role").val(temp);
                    });
                </script>
                <select class="form-control" name="role" id="id_role" value="{{ request.GET.role }}">
                    <option disabled value> -- Filter by Role -- </option>
                    <option value>All</option>
                    <option value="COMPOSER">Composer</option>
                    <option value="ARRANGER">Arranger</option>
                    <option value="AUTHOR">Author of Text</option>
                    <option value="TRANSCRIBER">Transcriber</option>
                    <option value="PERFORMER">Performer</option>
                    <option value="IMPROVISER">Improviser</option>
                </select>
            {% endif %}
            <input type="text" class="form-control" placeholder="Keyword" name="q" value="{{ request.GET.q}}">
            <div class="input-group-append">
                <button type="submit" class="btn btn-info btn-sm"> Filter </button>
            </div>
        </div>
    </form>
</div>